version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      ZOOKEEPER_CONNECT_STRING: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: localhost:9092
    ports:
      - "9092:9092"
      - "9000:9000"
